
import React, { useState } from 'react';
import MobilePreview from './components/MobilePreview';
import CodePanel from './components/CodePanel';
import SuggestionCard from './components/SuggestionCard';
import { generateAppCode } from './services/geminiService';
import { AppProject, Suggestion } from './types';

const App: React.FC = () => {
  const [project, setProject] = useState<AppProject | null>(null);
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState<'preview' | 'code' | 'docs'>('preview');

  const handleBuild = async (customPrompt?: string) => {
    const inputPrompt = customPrompt || prompt;
    if (!inputPrompt.trim()) return;

    setIsGenerating(true);
    try {
      const result = await generateAppCode(
        inputPrompt, 
        project?.code || null,
        project?.history.map(h => h.prompt) || []
      );

      const newVersion = {
        timestamp: Date.now(),
        code: result.code,
        prompt: inputPrompt
      };

      setProject(prev => ({
        id: prev?.id || Math.random().toString(36).substr(2, 9),
        name: result.name,
        description: inputPrompt,
        code: result.code,
        readme: result.readme,
        history: prev ? [...prev.history, newVersion] : [newVersion],
        suggestions: result.suggestions
      }));
      setPrompt('');
    } catch (error) {
      alert("Error generating project. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGitHubExport = () => {
    if (!project) return;
    const repoContent = `
# ${project.name}
Generated by AI Android Forge

## Files Prepared for GitHub:
1. README.md
2. App.tsx (Main Source)
3. index.html (Entry point)

---
${project.readme}
    `;
    
    const blob = new Blob([repoContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.name.toLowerCase().replace(/\s+/g, '-')}-github-package.md`;
    a.click();
    URL.revokeObjectURL(url);
    alert("Project structure exported as Markdown for easy GitHub Repository setup!");
  };

  return (
    <div className="flex h-screen w-full bg-[#0a0f1d] text-slate-200 overflow-hidden">
      {/* Sidebar - History & Suggestions */}
      <aside className="w-80 border-r border-slate-800 bg-[#0d1425] flex flex-col shadow-2xl z-10">
        <div className="p-6 border-b border-slate-800">
          <div className="flex items-center space-x-3 mb-1">
            <div className="w-10 h-10 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl flex items-center justify-center shadow-lg shadow-indigo-500/20">
              <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path></svg>
            </div>
            <div>
              <h1 className="text-lg font-bold tracking-tight text-white">Forge v2</h1>
              <p className="text-[10px] text-indigo-400 font-bold uppercase tracking-widest">GitHub Ready</p>
            </div>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4 space-y-6">
          {project ? (
            <>
              <section>
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-widest">Next Evolutions</h3>
                  <span className="w-4 h-4 rounded-full bg-indigo-500/20 flex items-center justify-center text-[10px] text-indigo-400 border border-indigo-500/30">3</span>
                </div>
                <div className="space-y-3">
                  {project.suggestions.map((s) => (
                    <SuggestionCard key={s.id} suggestion={s} onApply={handleBuild} />
                  ))}
                </div>
              </section>

              <section>
                <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-widest mb-3">Commit History</h3>
                <div className="space-y-2">
                  {project.history.slice().reverse().map((v, i) => (
                    <div key={i} className="p-3 bg-slate-800/10 border border-slate-800/50 rounded-lg text-xs group hover:border-slate-700 transition-colors">
                      <div className="flex items-center space-x-2 mb-1">
                        <svg className="w-3 h-3 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7h8m0 0l-4-4m4 4l-4 4m0 6H8m0 0l4 4m-4-4l4-4"></path></svg>
                        <span className="text-slate-500">{new Date(v.timestamp).toLocaleTimeString()}</span>
                      </div>
                      <p className="text-slate-400 line-clamp-2 italic">"{v.prompt}"</p>
                    </div>
                  ))}
                </div>
              </section>
            </>
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-center p-6 space-y-4 opacity-40">
              <svg className="w-16 h-16 text-slate-700" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"></path></svg>
              <p className="text-slate-400 text-sm">Waiting for your first architecture prompt...</p>
            </div>
          )}
        </div>
      </aside>

      {/* Main Content Workspace */}
      <main className="flex-1 flex flex-col relative bg-[#0a0f1d]">
        {/* Top Header */}
        <header className="h-16 border-b border-slate-800 bg-[#0d1425]/80 backdrop-blur-md flex items-center justify-between px-8 z-10">
          <div className="flex items-center space-x-4">
            {project && (
              <>
                <div className="flex items-center space-x-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                  <h2 className="text-md font-bold text-white tracking-tight">{project.name}</h2>
                </div>
                <div className="h-4 w-[1px] bg-slate-800"></div>
                <div className="flex space-x-1">
                  {['preview', 'code', 'docs'].map((tab) => (
                    <button 
                      key={tab}
                      onClick={() => setActiveTab(tab as any)}
                      className={`px-3 py-1 rounded-md text-xs font-bold uppercase tracking-widest transition-all ${activeTab === tab ? 'bg-indigo-600/10 text-indigo-400 border border-indigo-500/20' : 'text-slate-500 hover:text-slate-300'}`}
                    >
                      {tab}
                    </button>
                  ))}
                </div>
              </>
            )}
          </div>
          
          <div className="flex items-center space-x-3">
            {project && (
              <>
                <button 
                  onClick={handleGitHubExport}
                  className="bg-slate-800 hover:bg-slate-700 text-slate-200 px-4 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center space-x-2 border border-slate-700"
                >
                  <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.041-1.416-4.041-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                  <span>Export to GitHub</span>
                </button>
                <button 
                  onClick={() => alert("Packaging for Android Store...")}
                  className="bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center space-x-2 shadow-lg shadow-indigo-600/20"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                  <span>Build APK</span>
                </button>
              </>
            )}
          </div>
        </header>

        {/* Workspace Area */}
        <div className="flex-1 p-8 flex overflow-hidden">
          {activeTab === 'preview' ? (
            <div className="flex-1 flex flex-col items-center justify-center">
                 <MobilePreview code={project?.code || ''} />
            </div>
          ) : activeTab === 'code' ? (
            <div className="flex-1 flex flex-col">
               <CodePanel code={project?.code || ''} />
            </div>
          ) : (
            <div className="flex-1 flex flex-col bg-slate-900/50 border border-slate-800 rounded-xl overflow-auto p-8">
              <div className="max-w-3xl mx-auto prose prose-invert">
                <div className="bg-slate-800/50 p-4 rounded-lg mb-6 border border-indigo-500/20">
                  <p className="text-xs text-indigo-400 font-bold uppercase tracking-widest mb-1">GitHub README.md Preview</p>
                  <p className="text-[10px] text-slate-500">Automatically generated for your repository.</p>
                </div>
                <pre className="text-slate-300 whitespace-pre-wrap font-sans leading-relaxed">
                  {project?.readme || "Documentation will appear after generation."}
                </pre>
              </div>
            </div>
          )}
        </div>

        {/* Command Bar */}
        <div className="p-8 pt-0 mt-auto">
          <div className="max-w-4xl mx-auto relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-2xl blur opacity-20 group-focus-within:opacity-40 transition duration-1000"></div>
            <div className="relative bg-[#0d1425] border border-slate-800 rounded-xl p-2 shadow-2xl flex items-center space-x-2 focus-within:border-indigo-500/50 transition-all">
              <div className="pl-4">
                {isGenerating ? (
                   <div className="w-5 h-5 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
                ) : (
                  <svg className="w-5 h-5 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                )}
              </div>
              <input 
                type="text"
                placeholder={isGenerating ? "Forging your architecture..." : "Ask for a feature or describe your app idea..."}
                className="flex-1 bg-transparent border-none focus:ring-0 text-slate-100 placeholder-slate-600 p-3 text-sm"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleBuild()}
                disabled={isGenerating}
              />
              <button 
                onClick={() => handleBuild()}
                disabled={isGenerating || !prompt.trim()}
                className="bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed text-white px-6 py-2.5 rounded-lg font-bold text-xs uppercase tracking-widest transition-all active:scale-95"
              >
                {project ? "Update Project" : "Initialize Forge"}
              </button>
            </div>
          </div>
          <div className="flex justify-center space-x-6 mt-4 opacity-30 text-[10px] font-bold uppercase tracking-[0.25em]">
             <span>Ready for GitHub</span>
             <span>&bull;</span>
             <span>Android Optimized</span>
             <span>&bull;</span>
             <span>Gemini 3.0 Pro</span>
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;
